workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials  # Add your Apple Developer credentials here in Codemagic dashboard
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        # These will be set automatically by Codemagic when credentials are configured
        # APPLE_ID: your-apple-id@example.com
        # APPLE_APP_SPECIFIC_PASSWORD: your-app-specific-password
        # APPLE_TEAM_ID: your-team-id
      xcode: latest
      node: 22
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
          # Verify dist directory was created
          if [ ! -d "dist" ]; then
            echo "ERROR: dist directory was not created by build"
            exit 1
          fi
          echo "✅ Web app built successfully"
          echo "Dist directory contents:"
          ls -la dist/ | head -10
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
          echo "Capacitor CLI version:"
          npx cap --version
      - name: Verify Capacitor configuration
        script: |
          echo "Checking Capacitor configuration..."
          if [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.json" ]; then
            echo "ERROR: Capacitor config file not found"
            echo "Looking for config files:"
            ls -la capacitor.config.* 2>/dev/null || echo "No capacitor config files found"
            exit 1
          fi
          echo "✅ Capacitor config found"
          if [ -f "capacitor.config.ts" ]; then
            echo "Using capacitor.config.ts"
            cat capacitor.config.ts
          fi
      - name: Add iOS platform (if not exists)
        script: |
          echo "Checking for iOS platform..."
          if [ ! -d "ios" ]; then
            echo "iOS directory doesn't exist, adding platform..."
            echo "Current directory: $(pwd)"
            echo "Checking Capacitor config..."
            ls -la capacitor.config.* 2>/dev/null || echo "No capacitor config found"
            echo "Checking dist directory..."
            ls -la dist/ 2>/dev/null || echo "dist directory doesn't exist"
            npx cap add ios || {
              echo "Failed to add iOS platform"
              echo "Capacitor version:"
              npx cap --version || echo "Cannot get Capacitor version"
              exit 1
            }
            echo "iOS platform added, checking structure..."
            ls -la ios/ || echo "ios directory still doesn't exist"
          else
            echo "iOS platform already exists"
            echo "Contents of ios directory:"
            ls -la ios/
          fi
          # Capacitor 8 uses Swift Package Manager, not CocoaPods
          # Check for Package.swift or Podfile (for older versions)
          echo "Checking for iOS project files..."
          if [ -f "ios/App/Package.swift" ]; then
            echo "✅ Package.swift found (Capacitor 8 - Swift Package Manager)"
          elif [ -f "ios/App/Podfile" ]; then
            echo "✅ Podfile found (older Capacitor version - CocoaPods)"
          elif [ -f "ios/Podfile" ]; then
            echo "✅ Podfile found at ios/Podfile (older Capacitor version)"
          else
            echo "⚠️  Neither Package.swift nor Podfile found"
            echo "Searching for project files:"
            find ios -name "Package.swift" 2>/dev/null || echo "No Package.swift found"
            find ios -name "Podfile" 2>/dev/null || echo "No Podfile found"
            echo "Contents of ios/App:"
            ls -la ios/App/ 2>/dev/null || echo "ios/App doesn't exist"
            # For Capacitor 8, Package.swift might be optional or in a different location
            # Check if we have the Xcode project at least
            if [ -f "ios/App/App.xcodeproj/project.pbxproj" ]; then
              echo "✅ Xcode project found, continuing (Capacitor 8 may not need Package.swift)"
            else
              echo "❌ Xcode project not found either"
              echo "Attempting to re-add iOS platform..."
              rm -rf ios
              npx cap add ios || {
                echo "Failed to re-add iOS platform"
                exit 1
              }
              # Check again after re-adding
              if [ -f "ios/App/Package.swift" ] || [ -f "ios/App/App.xcodeproj/project.pbxproj" ]; then
                echo "✅ iOS project structure found after re-adding"
              else
                echo "❌ iOS project structure still not found after re-adding"
                exit 1
              fi
            fi
          fi
      - name: Install CocoaPods (only if Podfile exists)
        script: |
          # Capacitor 8 uses Swift Package Manager, so CocoaPods is only needed for older versions
          if [ -f "ios/App/Podfile" ] || [ -f "ios/Podfile" ]; then
            echo "Podfile found, installing CocoaPods..."
            which pod || gem install cocoapods
          else
            echo "No Podfile found - using Swift Package Manager (Capacitor 8)"
          fi
      - name: Sync Capacitor
        script: |
          echo "Syncing Capacitor iOS platform..."
          npx cap sync ios || {
            echo "Sync failed, checking iOS project structure..."
            ls -la ios/ || echo "ios directory doesn't exist"
            if [ -d "ios/App" ]; then
              ls -la ios/App/ || echo "Cannot list ios/App contents"
              # Only run pod install if Podfile exists (older Capacitor versions)
              if [ -f "ios/App/Podfile" ] || [ -f "ios/Podfile" ]; then
                echo "Podfile exists, attempting manual pod install..."
                cd ios/App
                pod install
                cd ../..
              else
                echo "No Podfile found - using Swift Package Manager"
                echo "Checking for Package.swift:"
                find ios -name "Package.swift" 2>/dev/null || echo "No Package.swift found"
              fi
            fi
            exit 1
          }
      - name: Verify iOS project structure
        script: |
          echo "Verifying iOS project structure..."
          if [ ! -d "ios/App" ]; then
            echo "ERROR: ios/App directory doesn't exist"
            exit 1
          fi
          echo "Checking for required files..."
          # Capacitor 8 uses Swift Package Manager, not CocoaPods
          if [ -f "ios/App/Podfile" ]; then
            echo "✅ Podfile found (older Capacitor version)"
            # For CocoaPods, we need the workspace
            if [ ! -f "ios/App/App.xcworkspace/contents.xcworkspacedata" ]; then
              echo "WARNING: App.xcworkspace not found, running pod install..."
              cd ios/App
              pod install || {
                echo "pod install failed"
                echo "Contents of ios/App:"
                ls -la
                exit 1
              }
              cd ../..
            fi
          elif [ -f "ios/App/Package.swift" ]; then
            echo "✅ Package.swift found (Capacitor 8 - Swift Package Manager)"
            # For Swift Package Manager, we use the .xcodeproj directly, not .xcworkspace
            if [ ! -f "ios/App/App.xcodeproj/project.pbxproj" ]; then
              echo "ERROR: App.xcodeproj not found"
              exit 1
            fi
          else
            echo "⚠️  Neither Podfile nor Package.swift found"
            echo "Checking for Xcode project..."
            if [ -f "ios/App/App.xcodeproj/project.pbxproj" ]; then
              echo "✅ Xcode project found, continuing"
            else
              echo "ERROR: No Xcode project found"
              echo "Contents of ios/App:"
              ls -la ios/App/
              exit 1
            fi
          fi
          echo "✅ iOS project structure verified"
      - name: Set up code signing
        script: |
          cd ios/App
          # Check if using workspace or project
          if [ -f "App.xcworkspace/contents.xcworkspacedata" ]; then
            XCODE_BUILD_ARG="-workspace App.xcworkspace"
          else
            XCODE_BUILD_ARG="-project App.xcodeproj"
          fi
          
          # Check if Apple Developer credentials are available
          if [ -n "$APPLE_TEAM_ID" ] && [ -n "$CM_CERTIFICATE" ]; then
            echo "✅ Apple Developer credentials found - using proper code signing"
            # Codemagic will handle code signing automatically when credentials are configured
            # Just verify the settings
            xcodebuild $XCODE_BUILD_ARG \
              -scheme App \
              -configuration Release \
              -showBuildSettings | grep -i "code_sign" || echo "Code signing will be handled by Codemagic"
          else
            echo "⚠️  No Apple Developer credentials found - building unsigned (for development)"
            # Disable code signing for development builds
            xcodebuild $XCODE_BUILD_ARG \
              -scheme App \
              -configuration Release \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEVELOPMENT_TEAM="" \
              PROVISIONING_PROFILE_SPECIFIER="" \
              -showBuildSettings | grep -i "code_sign" || echo "Code signing disabled"
            # Update project file for unsigned build
            if [ -f "App.xcodeproj/project.pbxproj" ]; then
              echo "Updating project file to disable code signing..."
              sed -i '' 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/g' App.xcodeproj/project.pbxproj 2>/dev/null || \
              sed -i 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/g' App.xcodeproj/project.pbxproj 2>/dev/null || true
              sed -i '' 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "";/g' App.xcodeproj/project.pbxproj 2>/dev/null || \
              sed -i 's/CODE_SIGN_IDENTITY = .*/CODE_SIGN_IDENTITY = "";/g' App.xcodeproj/project.pbxproj 2>/dev/null || true
              sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' App.xcodeproj/project.pbxproj 2>/dev/null || \
              sed -i 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' App.xcodeproj/project.pbxproj 2>/dev/null || true
            fi
          fi
          cd ../..
      - name: Build ipa for distribution
        script: |
          cd ios/App
          # Check if we're using CocoaPods (workspace) or Swift Package Manager (project)
          if [ -f "App.xcworkspace/contents.xcworkspacedata" ]; then
            echo "✅ Using CocoaPods workspace"
            WORKSPACE_ARG="-workspace App.xcworkspace"
          elif [ -f "App.xcodeproj/project.pbxproj" ]; then
            echo "✅ Using Swift Package Manager project"
            WORKSPACE_ARG="-project App.xcodeproj"
          else
            echo "ERROR: Neither workspace nor project found in ios/App/"
            echo "Current directory: $(pwd)"
            echo "Contents:"
            ls -la
            echo "Searching for workspace/project:"
            find . -name "*.xcworkspace" -type d 2>/dev/null || echo "No workspace found"
            find . -name "*.xcodeproj" -type d 2>/dev/null || echo "No project found"
            exit 1
          fi
          echo "Proceeding with build..."
          mkdir -p build
          # Build with or without code signing based on credentials
          if [ -n "$APPLE_TEAM_ID" ] && [ -n "$CM_CERTIFICATE" ]; then
            echo "Building with code signing (App Store ready)..."
            xcodebuild $WORKSPACE_ARG \
              -scheme App \
              -configuration Release \
              -destination generic/platform=iOS \
              -archivePath build/App.xcarchive \
              archive
          else
            echo "Building unsigned (development only)..."
            xcodebuild $WORKSPACE_ARG \
              -scheme App \
              -configuration Release \
              -destination generic/platform=iOS \
              -archivePath build/App.xcarchive \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO \
              DEVELOPMENT_TEAM="" \
              archive
          fi
          # Verify archive was created
          if [ ! -d "build/App.xcarchive" ]; then
            echo "ERROR: Archive was not created at build/App.xcarchive"
            echo "Contents of build directory:"
            ls -la build/ || echo "build directory doesn't exist"
            exit 1
          fi
          echo "Archive created successfully at build/App.xcarchive"
      - name: Create ExportOptions.plist
        script: |
          mkdir -p ios/App
          # Check if we have Apple Developer credentials for App Store distribution
          if [ -n "$APPLE_TEAM_ID" ] && [ -n "$CM_CERTIFICATE" ]; then
            echo "Creating ExportOptions.plist for App Store distribution..."
            cat > ios/App/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>method</key>
          	<string>app-store</string>
          	<key>teamID</key>
          	<string>${APPLE_TEAM_ID}</string>
          	<key>signingStyle</key>
          	<string>automatic</string>
          	<key>compileBitcode</key>
          	<false/>
          	<key>manageAppVersionAndBuildNumber</key>
          	<true/>
          </dict>
          </plist>
          EOF
          else
            echo "Creating ExportOptions.plist for development export (unsigned)..."
            cat > ios/App/ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>method</key>
          	<string>development</string>
          	<key>signingStyle</key>
          	<string>manual</string>
          	<key>compileBitcode</key>
          	<false/>
          	<key>manageAppVersionAndBuildNumber</key>
          	<false/>
          </dict>
          </plist>
          EOF
          fi
          echo "✅ ExportOptions.plist created"
      - name: Verify archive exists before export
        script: |
          if [ ! -d "ios/App/build/App.xcarchive" ]; then
            echo "ERROR: Archive not found at ios/App/build/App.xcarchive"
            echo "Searching for archive files..."
            find ios -name "*.xcarchive" -type d 2>/dev/null || echo "No .xcarchive files found"
            echo "Contents of ios/App/build:"
            ls -la ios/App/build/ 2>/dev/null || echo "ios/App/build directory doesn't exist"
            exit 1
          fi
          echo "Archive found, proceeding with export..."
      - name: Export IPA
        script: |
          mkdir -p ios/App/build/export
          # For unsigned development builds, we may need to skip export or use a workaround
          # Try export first, but if it fails due to signing, we'll create a workaround
          xcodebuild -exportArchive \
            -archivePath ios/App/build/App.xcarchive \
            -exportPath ios/App/build/export \
            -exportOptionsPlist ios/App/ExportOptions.plist \
            -allowProvisioningUpdates || {
            echo "Export failed, attempting alternative method..."
            # Alternative: Extract the app from the archive and create IPA manually
            if [ -d "ios/App/build/App.xcarchive/Products/Applications/App.app" ]; then
              echo "Creating IPA manually from archive..."
              cd ios/App/build/export
              mkdir -p Payload
              cp -r ../App.xcarchive/Products/Applications/App.app Payload/
              zip -r App.ipa Payload
              rm -rf Payload
              cd ../../../../..
              echo "✅ IPA created manually"
            else
              echo "ERROR: Could not find app in archive"
              exit 1
            fi
          }
          # Verify IPA was created
          if ls ios/App/build/export/*.ipa 1> /dev/null 2>&1; then
            echo "✅ IPA exported successfully"
            ls -lh ios/App/build/export/*.ipa
          else
            echo "WARNING: IPA file may not have been created"
            echo "Contents of export directory:"
            ls -la ios/App/build/export/ || echo "export directory is empty or doesn't exist"
          fi
    artifacts:
      - ios/App/build/export/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

