workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 22
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Initialize Capacitor (if needed)
        script: |
          if [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.ts" ]; then
            echo "Capacitor not initialized, but config file exists - continuing"
          fi
      - name: Add iOS platform (if not exists)
        script: |
          if [ ! -d "ios" ]; then
            echo "Adding iOS platform..."
            npx cap add ios
          else
            echo "iOS platform already exists"
          fi
          # Verify Podfile exists
          if [ ! -f "ios/App/Podfile" ] && [ ! -f "ios/Podfile" ]; then
            echo "Warning: Podfile not found after adding iOS platform"
            echo "Attempting to re-add iOS platform..."
            rm -rf ios
            npx cap add ios
          fi
      - name: Install CocoaPods (if needed)
        script: |
          which pod || gem install cocoapods
      - name: Sync Capacitor
        script: |
          echo "Syncing Capacitor iOS platform..."
          npx cap sync ios || {
            echo "Sync failed, checking iOS project structure..."
            ls -la ios/ || echo "ios directory doesn't exist"
            if [ -d "ios/App" ]; then
              ls -la ios/App/ || echo "Cannot list ios/App contents"
              if [ -f "ios/App/Podfile" ]; then
                echo "Podfile exists, attempting manual pod install..."
                cd ios/App
                pod install
                cd ../..
              else
                echo "Podfile not found at ios/App/Podfile"
                find ios -name "Podfile" 2>/dev/null || echo "No Podfile found anywhere"
              fi
            fi
            exit 1
          }
      - name: Set up code signing settings on Xcode project
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            archive | xcpretty
      - name: Create ExportOptions.plist if needed
        script: |
          if [ ! -f "ios/App/ExportOptions.plist" ]; then
            mkdir -p ios/App
            cat > ios/App/ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>method</key>
          	<string>development</string>
          	<key>teamID</key>
          	<string></string>
          	<key>signingStyle</key>
          	<string>automatic</string>
          	<key>compileBitcode</key>
          	<false/>
          </dict>
          </plist>
          EOF
          fi
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios/App/build/App.xcarchive \
            -exportPath ios/App/build/export \
            -exportOptionsPlist ios/App/ExportOptions.plist
    artifacts:
      - ios/App/build/export/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

