workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 22
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Add iOS platform (if not exists)
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build ipa for distribution
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            archive | xcpretty
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ios/App/ExportOptions.plist
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

