workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
      node: 22
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web app
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Add iOS platform (if not exists)
        script: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing settings on Xcode project
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
            -scheme App \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Build ipa for distribution
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            archive | xcpretty
      - name: Create ExportOptions.plist if needed
        script: |
          if [ ! -f "ios/App/ExportOptions.plist" ]; then
            mkdir -p ios/App
            cat > ios/App/ExportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
          	<key>method</key>
          	<string>development</string>
          	<key>teamID</key>
          	<string></string>
          	<key>signingStyle</key>
          	<string>automatic</string>
          	<key>compileBitcode</key>
          	<false/>
          </dict>
          </plist>
          EOF
          fi
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath ios/App/build/App.xcarchive \
            -exportPath ios/App/build/export \
            -exportOptionsPlist ios/App/ExportOptions.plist
    artifacts:
      - ios/App/build/export/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false

